// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc862.glitch.commands;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.CommandGroup;
import edu.wpi.first.wpilibj.command.TimedCommand;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import org.usfirst.frc862.glitch.Robot;
import org.usfirst.frc862.glitch.paths.*;
import org.usfirst.frc862.glitch.subsystems.ShineBois;
import org.usfirst.frc862.util.DynamicPathCommandBase;

/**
 *
 */
public class SmartAuton extends Command {
    private boolean scale_auton;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public SmartAuton() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.shifter);
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
        ShineBois.rainbow();
        scale_auton = false;
//        Robot.shifter.forceDownShift();

        CommandGroup cmd = new CommandGroup();
  //      cmd.addSequential(new DownShift());

        cmd.addSequential(new MoveCollectorToGround(), 1);

        if (Robot.getAutonDelay() > 0) {
            cmd.addSequential(new TimedCommand(Robot.getAutonDelay()));
        }

        cmd.addParallel(new HoldCube());

        if (Robot.startOnLeft()) {
            if (Robot.switchOnLeft()) {
                cmd.addParallel(new MoveCollectorToSwitch());
                cmd.addSequential(new LeftPointsSwitch());
            } else if (Robot.scaleOnLeft()) {
                DynamicPathCommandBase path = new LeftScaleNearLG();

                CommandGroup riseUp = new CommandGroup();
                riseUp.addSequential(new TimedCommand(path.duration() - 3));
                riseUp.addSequential(new MoveCollectorToScale());
                cmd.addParallel(riseUp);
                cmd.addSequential(path);

            } else {
                DynamicPathCommandBase path = new LeftScaleFarLG();

                CommandGroup riseUp = new CommandGroup();
                riseUp.addSequential(new TimedCommand(path.duration() - 3));
                riseUp.addSequential(new MoveCollectorToScale());

                cmd.addParallel(riseUp);
                cmd.addSequential(path);
            }
        } else {
            if (!Robot.switchOnLeft()) {
                DynamicPathCommandBase path = new RightPointsSwitch();
                cmd.addParallel(new MoveCollectorToSwitch());
                cmd.addSequential(path);
                //cmd.addParallel(new HoldCube());
            } else if (!Robot.scaleOnLeft()) {
                scale_auton = true;
                DynamicPathCommandBase path = new RightScaleNear();
                CommandGroup raiseUp = new CommandGroup();
//                raiseUp.addSequential(new TimedCommand(path.duration() - 3.5));
                raiseUp.addSequential(new MoveCollectorToScale());
                cmd.addParallel(raiseUp);
                cmd.addSequential(path);
            } else {
                scale_auton = true;
                DynamicPathCommandBase path = new RightScaleFar();
                CommandGroup raiseUp = new CommandGroup();
                raiseUp.addSequential(new TimedCommand(path.duration() - 2.8));
                cmd.addParallel(raiseUp);
                cmd.addSequential(path);
            }
        }

        cmd.addSequential(new EjectCube(), 0.5);

        if (scale_auton) {
            CommandGroup readyToCollect = new CommandGroup();
            readyToCollect.addSequential(new TimedCommand(0.5));
            readyToCollect.addSequential(new MoveCollectorToCollect());
            cmd.addParallel(readyToCollect);

            double angle1 = SmartDashboard.getNumber("Auto Angle 1", 862);
            double angle2 = SmartDashboard.getNumber("Auto Angle 1", 862);

            if (Robot.startOnLeft()) {
                if (Robot.scaleOnLeft()) {
                    cmd.addSequential(new TurnToAbsolutePosition((angle1 < 360) ? angle1 : 160));
                    cmd.addSequential(new TurnToAbsolutePosition((angle1 < 360) ? angle1 : 160));
                } else {
                    cmd.addSequential(new TurnToAbsolutePosition((angle1 < 360) ? angle1 : -150));
                    cmd.addSequential(new TurnToAbsolutePosition((angle1 < 360) ? angle1 : -150));
                }
            } else {
                if (Robot.scaleOnLeft()) {
                    cmd.addSequential(new TurnToAbsolutePosition((angle1 < 360) ? angle1 : -150));
                    cmd.addSequential(new TurnToAbsolutePosition((angle1 < 360) ? angle1 : -150));
                } else {
                    cmd.addSequential(new TurnToAbsolutePosition((angle1 < 360) ? angle1 : 160));
                    cmd.addSequential(new TurnToAbsolutePosition((angle1 < 360) ? angle1 : 160));
                }
            }

            if (Robot.attemptMultiCubeAuton()) {
                cmd.addSequential(new MoveCollectorToCollect(), 1);
                cmd.addParallel(new HoldCube());
                cmd.addSequential(new DriveForwardToCube());
                cmd.addSequential(new GentleCollectCube());

                if (Robot.scaleOnLeft()) {
                    cmd.addSequential(new TurnToAbsolutePosition((angle2 < 360) ? angle2 : 0));
                    cmd.addSequential(new TurnToAbsolutePosition((angle2 < 360) ? angle2: 0));
                } else {
                    cmd.addSequential(new TurnToAbsolutePosition((angle2 < 360) ? angle2: 0));
                    cmd.addSequential(new TurnToAbsolutePosition((angle2 < 360) ? angle2: 0));
                }

                cmd.addSequential(new MoveCollectorToScale(), 1);
                cmd.addSequential(new DriveForwardToScale());

                cmd.addSequential(new EjectCube(), 0.5);
                cmd.addSequential(new TurnToAbsolutePosition(180));
                cmd.addSequential(new MoveCollectorToCollect());
            }
        } else {
            cmd.addSequential(new BackupSlow());
            cmd.addSequential(new MoveCollectorToCollect());
        }

        cmd.start();
    }

    @Override
    protected boolean isFinished() {
        return true;
    }
}
