// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc862.glitch.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc862.glitch.paths.StraightSwitch;
import org.usfirst.frc862.util.StatefulCommand;

/**
 *
 */
public class TestStatefulAuton extends StatefulCommand {
    private Command cmd;

    enum States {
        Position, Drive, Eject, Finished
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
    public TestStatefulAuton() {
        super(States.Position);
    }

    public void positionEnter() {
        cmd = new MoveCollectorToSwitch();
        cmd.start();
    }

    public void position() {
        if (cmd.isCompleted()) {
            setState(States.Drive);
        }
    }

    public void driveEnter() {
        cmd = new StraightSwitch();
        cmd.start();
    }

    public void drive() {
        if (cmd.isCompleted()) {
            setState(States.Eject);
        }
    }

    public void ejectEnter() {
        cmd = new EjectCube();
        cmd.start();
    }

    public void eject() {
        if (cmd.isCompleted()) {
            setState(States.Finished);
        }
    }

    @Override
    protected boolean isFinished() {
        return getState() == States.Finished;
    }
}
