// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc862.glitch.subsystems;

import java.util.ArrayList;

import org.usfirst.frc862.glitch.Constants;
import org.usfirst.frc862.glitch.vision.CubeNotFoundException;
import org.usfirst.frc862.glitch.vision.PowerCube;

import edu.wpi.first.wpilibj.SerialPort;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

//import org.usfirst.frc862.util.SerialReader;

/**
 *
 */
public class CubeVision extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	
	
	private int framesSinceContact;
	private int lastGoodFrameNum;
	private SerialPort serialIn;
	private ArrayList<PowerCube> cubes;
//	private BufferedReader sbuffer;
	
	public CubeVision() {
		super();
		cubes = new ArrayList();
		serialIn = new SerialPort(115200, SerialPort.Port.kUSB);
		serialIn.writeString("streamon\n");
//		sbuffer = new BufferedReader(new SerialReader(serialIn));
		//serialIn.enableTermination();
		framesSinceContact = 0;
		
	}

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop
    	/*
    	 * Example input
    	 * Frame:378378, Process Time:23.0 fps, 108.4% CPU, 34C, 1344 MHz, Objects:1=
		 * Object:0[x:240,y:191,w:93,h:114]
    	 */
    	
    	//TODO enable termination and setup collection loop
    	String inData = serialIn.readString();
    	//Logger.info(inData);
    	if(inData.indexOf("=") != -1) {
	//    	String inData = sbuffer.readLine();
	    	SmartDashboard.putString("dataIn", inData);
	    	SmartDashboard.putString("step", "dataIn");
	    	String lastFrame = inData.substring(inData.lastIndexOf("Frame"));
	    	SmartDashboard.putString("lastFrame", lastFrame);
	    	SmartDashboard.putString("step", "lastFrame");
	    	int frameNum = Integer.parseInt(lastFrame.substring(lastFrame.indexOf("Frame:") + 6, lastFrame.indexOf(",")));
	    	SmartDashboard.putNumber("frameNum", frameNum);
	    	int numObjects = Integer.parseInt(lastFrame.substring(lastFrame.indexOf("Objects:") + 8, lastFrame.indexOf("=")));
	    	SmartDashboard.putNumber("numObjects", numObjects);
	    	SmartDashboard.putString("step", "getNums");
	    	if(numObjects > 0 && lastFrame.endsWith("]\r\n")) {
	    		cubes.clear();
	    		framesSinceContact = 0;
	    		String currentCube;
	    		for(int i = 0; i < numObjects; i++) {
	    			currentCube = lastFrame.substring(lastFrame.indexOf("Object:" + i + "["));
	    	    	SmartDashboard.putString("step", "currentCube" + i);
	    			SmartDashboard.putString("currentCube", currentCube);
	    			int x, y, w, h;
	    			x = Integer.parseInt(currentCube.substring(currentCube.indexOf("x:") + 2, currentCube.indexOf(",", currentCube.indexOf("x:"))));
	    			y = Integer.parseInt(currentCube.substring(currentCube.indexOf("y:") + 2, currentCube.indexOf(",", currentCube.indexOf("y:"))));
	    			w = Integer.parseInt(currentCube.substring(currentCube.indexOf("w:") + 2, currentCube.indexOf(",", currentCube.indexOf("w:"))));
	    			h = Integer.parseInt(currentCube.substring(currentCube.indexOf("h:") + 2, currentCube.indexOf(",", currentCube.indexOf("h:"))));
	    			SmartDashboard.putString("step", "m");
	    			double m = Double.parseDouble(currentCube.substring(currentCube.indexOf("m:") + 2, currentCube.indexOf("]", currentCube.indexOf("m:"))));
	    	    	SmartDashboard.putString("step", "xywh");
	    			
	    	    	SmartDashboard.putNumber("m", m);
	    			if(!(w / h >= 2.2 || h / w >= 2.2 || w >= 320 || h >= 250 || (w * h) >= 40000 || m > 3)) cubes.add(new PowerCube(x, y, w, h));
	    			SmartDashboard.putNumber("cubes.size()", cubes.size());
	    	    	SmartDashboard.putString("step", "push");
	    		}
	    		lastGoodFrameNum = frameNum;
	    	}
	    	else {
	    		framesSinceContact = frameNum - lastGoodFrameNum;
	    		SmartDashboard.putNumber("framesSinceContact", framesSinceContact);
	        	SmartDashboard.putString("step", "noObjects");
	    	}
    	}

    }
    
    /**
     * 
     * @return double[] {angle (degrees), area (pixels)}
     * @throws CubeNotFoundException throws if no cubes have been identified for a number of frames and contains the number of frames since contact for logging
     */
    public double[] getBestCube() throws CubeNotFoundException {
    	if(framesSinceContact > Constants.VISION_ABORT_THRESHOLD) throw new CubeNotFoundException(framesSinceContact);
    	if(cubes.size() == 0) throw new CubeNotFoundException();
    	
    	double[] vals = {0.0, 0.0};
    	double smallestAngle = Math.abs(cubes.get(0).getAngle());
    	int bestCubeIndex = 0;
    	for(int i = 1; i < cubes.size(); i++) {
    		if(Math.abs(cubes.get(i).getAngle()) < smallestAngle) {
    			bestCubeIndex = i;
    			smallestAngle = Math.abs(cubes.get(i).getAngle());
    		}
    	}
    	vals[0] = cubes.get(bestCubeIndex).getAngle();
    	vals[1] = cubes.get(bestCubeIndex).getArea();
    	
    	return vals;
    	
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    

}

