// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc862.glitch.subsystems;

import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.FeedbackDevice;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import org.usfirst.frc862.glitch.Constants;
import org.usfirst.frc862.glitch.RobotMap;
import org.usfirst.frc862.glitch.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class FourBar extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final WPI_TalonSRX motor = RobotMap.fourBarmotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public FourBar() {
        super();
        motor.configSelectedFeedbackSensor(FeedbackDevice.QuadEncoder, 0, Constants.TALON_TIMEOUT);
        motor.configAllowableClosedloopError(0, Constants.FOURBAR_ALLOWABLE_ERROR, Constants.TALON_TIMEOUT);
        motor.config_kP(0, Constants.FOURBAR_P, Constants.TALON_TIMEOUT);
        motor.config_kI(0, Constants.FOURBAR_I, Constants.TALON_TIMEOUT);
        motor.config_kD(0, Constants.FOURBAR_D, Constants.TALON_TIMEOUT);
        motor.config_kF(0, Constants.FOURBAR_F, Constants.TALON_TIMEOUT);

        motor.configMotionAcceleration(Constants.FOURBAR_ACC, Constants.TALON_TIMEOUT);
        motor.configMotionCruiseVelocity(Constants.FOURBAR_VEL, Constants.TALON_TIMEOUT);

        SmartDashboard.putNumber("Fourbar Allowable Error", Constants.FOURBAR_ALLOWABLE_ERROR);
        SmartDashboard.putNumber("Fourbar P", Constants.FOURBAR_P);
        SmartDashboard.putNumber("Fourbar I", Constants.FOURBAR_I);
        SmartDashboard.putNumber("Fourbar D", Constants.FOURBAR_D);
        SmartDashboard.putNumber("Fourbar F", Constants.FOURBAR_F);

        SmartDashboard.putNumber("Fourbar ACC", Constants.FOURBAR_ACC);
        SmartDashboard.putNumber("Fourbar VEL", Constants.FOURBAR_VEL);
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new ControlFourBar());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop
        int err = (int) SmartDashboard.getNumber("Fourbar Allowable Error", Constants.FOURBAR_ALLOWABLE_ERROR);
        motor.configAllowableClosedloopError(0, err, Constants.TALON_TIMEOUT);
        double kP = SmartDashboard.getNumber("Fourbar P", Constants.FOURBAR_P);
        motor.config_kP(0, kP, Constants.TALON_TIMEOUT);
        double kI = SmartDashboard.getNumber("Fourbar I", Constants.FOURBAR_I);
        motor.config_kI(0, kI, Constants.TALON_TIMEOUT);
        double kD = SmartDashboard.getNumber("Fourbar D", Constants.FOURBAR_D);
        motor.config_kD(0, kD, Constants.TALON_TIMEOUT);
        double kF = SmartDashboard.getNumber("Fourbar F", Constants.FOURBAR_F);
        motor.config_kF(0, kF, Constants.TALON_TIMEOUT);

        int acc = (int) Math.round(SmartDashboard.getNumber("Fourbar Acc", Constants.FOURBAR_ACC));
        motor.configMotionAcceleration(acc, Constants.TALON_TIMEOUT);
        int vel = (int) Math.round(SmartDashboard.getNumber("Fourbar Vel", Constants.FOURBAR_VEL));
        motor.configMotionCruiseVelocity(vel, Constants.TALON_TIMEOUT);

        SmartDashboard.putNumber("FourBar Encoder", motor.getSelectedSensorPosition(0));
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public int getPositionEnc() {
        return motor.getSelectedSensorPosition(0);
    }

    public void moveToScale() {
        RobotMap.fourBarmotor.set(ControlMode.MotionMagic, Constants.FOURBAR_SCALE_POS);
    }

    public void moveToSwitch() {
            RobotMap.fourBarmotor.set(ControlMode.MotionMagic, Constants.FOURBAR_SWITCH_POS);
    }

    public void moveToBottom() {
        RobotMap.fourBarmotor.set(ControlMode.MotionMagic, Constants.FOURBAR_BOTTOM_POS);
    }

    public void moveToCollect() {
        RobotMap.fourBarmotor.set(ControlMode.MotionMagic, Constants.FOURBAR_COLLECT_POS);
    }
}

