// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc862.glitch.subsystems;

import edu.wpi.first.wpilibj.Timer;
import org.usfirst.frc862.glitch.Constants;
import org.usfirst.frc862.glitch.Robot;
import org.usfirst.frc862.glitch.RobotMap;
import edu.wpi.first.wpilibj.command.Subsystem;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.DigitalOutput;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class ShineBois extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final DigitalOutput seventh = RobotMap.shineBoisSeventh;
    private final DigitalOutput eighth = RobotMap.shineBoisEighth;
    private final DigitalOutput ninth = RobotMap.shineBoisNinth;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    private enum states {green, purple, rainbow, chase, off}
    private static states current = states.off;
    private static states alert = states.off;

    private static double alertEnd = 0;

    @Override
    public void periodic() {
        // Put code here to be run every loop

        if (alertEnd > Timer.getFPGATimestamp()) {
            setLEDColor(alert);
        } else {
            if (alert != states.off) {
                alert = states.off;
                Robot.oi.rumbleOff();
            }

            setLEDColor(current);
        }
    }

    private void setLEDColor(states state) {
        switch (state) {
            case green:
                stateGreen();
                break;
            case purple:
                statePurple();
                break;
            case rainbow:
                stateRainbow();
                break;
            case chase:
                stateChase();
                break;
            case off:
                stateOff();
                break;
        }
    }

    /*
    switch (state) {
    case 0:
      reset();
      break;
    case 1:
      green();
      break;
    case 2:
      orangeBlueChase();
      break;
    case 3:
      rainbow();
      break;
    case 4:
      purple();
      break;
    default:
      reset();
      break;
  }
  */

    public static void cubeCollected() {
        green();
        Robot.oi.rumbleOn();
    }

    public static void green() {
        alert = states.green;
        alertEnd = Timer.getFPGATimestamp() + Constants.ALERT_DURATION;

    }

    public static void purple() {
        alert = states.purple;
        alertEnd = Timer.getFPGATimestamp() + Constants.ALERT_DURATION;
    }

    public static void rainbow() {
        current = states.rainbow;
    }

    public static void chase() {
        current = states.chase;
    }

    public static void reset() {
        current = states.off;
        alert = states.off;
    }

    private static void stateGreen() {
        RobotMap.shineBoisEighth.set(false);
        RobotMap.shineBoisNinth.set(false);
        RobotMap.shineBoisSeventh.set(true);
    }

    private static void stateChase() {
        RobotMap.shineBoisSeventh.set(false);
        RobotMap.shineBoisNinth.set(false);
        RobotMap.shineBoisEighth.set(true);
    }

    private static void statePurple() {
        RobotMap.shineBoisSeventh.set(false);
        RobotMap.shineBoisEighth.set(false);
        RobotMap.shineBoisNinth.set(true);
    }

    private static void stateRainbow() {
        RobotMap.shineBoisNinth.set(false);
        RobotMap.shineBoisSeventh.set(true);
        RobotMap.shineBoisEighth.set(true);
    }

    private static void stateOff() {
        RobotMap.shineBoisSeventh.set(false);
        RobotMap.shineBoisEighth.set(false);
        RobotMap.shineBoisNinth.set(false);
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.


}

